### ISSUE TITLE
Bubbles: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#10]

**Comment by LRufenacht** [comment]
![image](https://user-images.githubusercontent.com/21205878/156829314-4716fcd6-51e2-4545-b0b3-4f275d274d0e.png)

- [ ] Fix description
- [ ] Use a TextBox and Button to show the Bubbles notification, it looks kind of weird on the DGV
- [ ] Fix Source Code link
- [ ] Add bubble click event
- [ ] Add demo minimum size

**Comment by AlaaTrAce** [comment]
Totally forgot to update you on this one,
![msedge_Q3t3aJ6rlP](https://user-images.githubusercontent.com/57464198/157466887-a47fe706-1f71-4a4c-83c9-76fade6667fb.png)

**Comment by LRufenacht** [comment]
Increase the vertical space between the button and TextBox, decrease the height of the textbox, and center both controls vertically.

Then you can close it!
