### ISSUE TITLE
DevExtreme - dxDateBox - Styling mode control diferent of property intial value

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#100]
the control visual styling is different respect the property initial value 
When I change other property, the control also change the styling and a first impression is something its wrong

![image](https://user-images.githubusercontent.com/7750628/167957289-52b5c8fe-6a58-48fc-ae06-c13f7c109363.png)

If at first step I change the "Accept Custom Vale" also change the styling. 
2 properties was changed but I only modified one
![image](https://user-images.githubusercontent.com/7750628/167957617-7189ef2d-d08d-4e77-9da4-04c1b57781dc.png)

**Comment by keevBush** [comment]
Just inverted values in styling mode. Fixed

**Comment by LRufenacht** [comment]
@keevBush it still doesn't work for me with latest from GitHub.
