### ISSUE TITLE
DevExtreme - dxDiagram : Unit and Autozoom changes don't reflect visual changes in control

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#101]
Changes in this properties Unit and Auto Zoom don't have visual changes in control 
The others ones does it

![image](https://user-images.githubusercontent.com/7750628/167958594-50a0001d-4529-4aa2-a216-107f8fd4028b.png)

**Comment by LRufenacht** [comment]
@keevBush please update this thread when fixed.

**Comment by keevBush** [comment]
@paulcordova just unit it's for the operating side. AutoZoom works
