### ISSUE TITLE
DevExtreme - Invalid License warning

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#102]
Running from demo.wisej.com:
![image](https://user-images.githubusercontent.com/37643082/167965191-ad84b363-1a51-48f2-bf6e-a69153482485.png)

**Comment by lucapivato** [comment]
Perfect, I saw it but couldn't reproduce anymore. Will attach. Any particular step?

**Comment by FrankITG** [comment]
Don´t think so, just opening this
https://demo.wisej.com/DevExtreme/#dxBullet

**Comment by LRufenacht** [comment]
https://github.com/iceteagroup/Wisej-QA/issues/566#issuecomment-1124408560 (please log an issue in QA if needed)
