### ISSUE TITLE
DevExtreme - dxHtmlEditor throws an exception

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#103]
Happens directly on opening the sample:

![image](https://user-images.githubusercontent.com/37643082/167977352-df1cdead-7774-4d52-908c-28fb7cc9e063.png)

**Comment by FrankITG** [comment]
Same problem for dfFileManager.

**Comment by keevBush** [comment]
Removed SelectedIndex on UserComboBox. Fixed
