### ISSUE TITLE
DevExtreme - dxColorBox label cut off

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#104]
![image](https://user-images.githubusercontent.com/37643082/167977427-fc1d1958-b6bd-482a-b571-d60370f925e1.png)

**Comment by keevBush** [comment]
It's a problem of size, change to autosize but same. Do you have another solution for the automatic line break and the automatic size?

**Comment by AlaaTrAce** [comment]
I recall this being an issue with the font itself, it appears that it's not properly installed on the server.
I think we should update the mixin with the fixes done by Luca for the regular DemoBrowser.
@LRufenacht what do you think?
