### ISSUE TITLE
DevExtreme - Invalid Server License when refresh browser

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#107]
Into any test, if I hit F5/refresh button of browser, a message appears "Invalid license server"

![image](https://user-images.githubusercontent.com/7750628/167961739-88abe918-e251-41ab-bf0e-2e688546195a.png)

**Comment by LRufenacht** [comment]
[See (please log an issue in QA if needed)](https://github.com/iceteagroup/Wisej-QA/issues/566#issuecomment-1124408560)
