### ISSUE TITLE
OfficeViewer: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#11]

**Comment by LRufenacht** [comment]
![image](https://user-images.githubusercontent.com/21205878/156830556-66276aed-2d79-4b4d-9a29-8f48cebfbc24.png)

- [ ] Buttons too small. Icons touching borders. Maybe use the left-hand side instead.
- [ ] Source code link

**Comment by AlaaTrAce** [comment]
![msedge_wsQPZ5UQeq](https://user-images.githubusercontent.com/57464198/156886367-3299c670-7371-426d-a40f-a32c29822de1.png)

**Comment by LRufenacht** [comment]
Better!

You can center-align those items or use the "Examples" bar like I showed in the other demo to allow the user to switch between them.

The Examples bar might look a little nicer but this is okay too.

**Comment by LRufenacht** [comment]
Feel free to close this one when you feel it's done.
