### ISSUE TITLE
DevExtreme - dxDiagram isn't resized properly when we collapse the Demos panel

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#111]
Default:
<img width="1440" alt="Screen Shot 2022-05-12 at 12 20 30 PM" src="https://user-images.githubusercontent.com/57464198/168065080-a3a01b06-7abc-4087-8548-16dc60df1c77.png">

Collapsed panel:
<img width="1440" alt="Screen Shot 2022-05-12 at 12 20 39 PM" src="https://user-images.githubusercontent.com/57464198/168065161-836b439b-d5c3-4bfa-b688-93480232507b.png">

**Comment by keevBush** [comment]
Video : https://drive.google.com/file/d/1t5T2HpJ4_MTwGlVvKXa9SYycU17Or9pi/view?usp=sharing

It work but it isn't appear directly like other component. more details in video
