### ISSUE TITLE
DevExtreme: Convert all JSON configurations to C# equivalent.

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/wisej-demobrowser#112]
Please convert all JSON configurations to their C# equivalents.

The C# Widget initialization code should be in the `DemoName_Load` handler and should be directly underneath the Demo constructor (see dxBullet for a completed sample).

After conversion, please test all the configuration options on the view to make sure they show a visual change to the widget.

**Comment by LRufenacht** [comment]
@keevBush @AlaaTrAce any progress here?

**Comment by keevBush** [comment]
@LRufenacht I'll push late this night I'm doing more test before push

**Comment by AlaaTrAce** [comment]
@keevBush if you want you can push the updates and I'll take a look with you.

**Comment by keevBush** [comment]
Done and push 👍🏽

**Comment by LRufenacht** [comment]
@AlaaTrAce @keevBush if this issue is fully completed and checked in you can close this issue.

**Comment by AlaaTrAce** [comment]
@keevBush can we close this or is there something pending?
