### ISSUE TITLE
IgniteUI: Convert all JSON configurations to C# equivalent.

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#113]
Please convert all JSON configurations to their C# equivalents.

The C# Widget initialization code should be in the DemoName_Load handler and should be directly underneath the Demo constructor (see igHierarchicalGrid for a completed sample).

After conversion, please test all the configuration options on the view to make sure they show a visual change to the widget.

**Comment by LRufenacht** [comment]
@keevBush @AlaaTrAce any progress here?

**Comment by AlaaTrAce** [comment]
This task is complete :).

**Comment by LRufenacht** [comment]
@AlaaTrAce @keevBush if this issue is fully completed and checked in you can close this issue.
