### ISSUE TITLE
KendoUI: Convert all JSON configurations to C# equivalent. 

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#114]
Same thing but for Kendo.

**Comment by LRufenacht** [comment]
@AlaaTrAce if this issue is fully completed and checked in you can close this issue.

**Comment by AlaaTrAce** [comment]
All is good and tested, found some issues present in both the updated version and the online version we have. 
Will create issues and attempt to fix them.
