### ISSUE TITLE
DevExtreme - dxFileManager

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#116]
minor possible issue:
Clicking on update (e.g. after just changing the Item View Mode) always fires a currentDirectoryChanged event.
Dunno if this is by design?

**Comment by keevBush** [comment]
the ui is recreated, refreshed  and must go the same path. I think because of that.

**Comment by LRufenacht** [comment]
Fixed and checked in.

Now it checks to see if the fileSystemProvider property actually changes before feeding it to their Widget.option({}) configuration updater.

It's really a "them" issue but should work for us now.
