### ISSUE TITLE
KendoUI - KendoAutoComplete's clear button doesn't work and toggling "Suggest" property probably doesn't work either.

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#118]
Clicking on the clear button on a kendoAutoComplete widget's doesn't do anything.
Also the when fiddeling with the Suggest property, I don't really see any difference in the functionality.
![dUEkvOu4bM](https://user-images.githubusercontent.com/57464198/171276870-e35628c6-1a1f-4750-b897-bc7d7934461f.gif)

**Comment by LRufenacht** [comment]
A kendo-side bug. Now I just recreate the widget if that property gets changed.
