### ISSUE TITLE
TableLayoutPanel: Features

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#12]

**Comment by LRufenacht** [comment]
![image](https://user-images.githubusercontent.com/21205878/156830074-770db64e-c072-4917-a8c9-1307450be3fe.png)

This one looks great!

A few minor things
- [ ] Needs to resize nicely for smaller screens. Boxes get cut off. Maybe find a way to rearrange the boxes?
- [ ] Tooltip gets cut off on "sales manager" boxes
- [ ] "Opportunities"
- [ ] Fix source code link

**Comment by AlaaTrAce** [comment]
![msedge_LduMC1BD4Z](https://user-images.githubusercontent.com/57464198/156886335-37e20366-d027-41f2-8d81-5bac9faca611.png)
Updated layout

- [ ] Find a better color scheme.

**Comment by AlaaTrAce** [comment]
This should be marginally better IMHO
![msedge_n1LU93dR9N](https://user-images.githubusercontent.com/57464198/157784339-fdcb8320-8dd8-4e5a-99bf-db73f0f80c51.png)

The rounded corners are part of the Bootstrap-4 theme, so I'm a bit confused of what to do about it (although with a white background it's barely noticeable)
Here's a screenshot with a Blue theme for reference:
![msedge_HWjCzmYMls](https://user-images.githubusercontent.com/57464198/157784469-2be9914e-0a6b-4f17-a7b6-a1260afb1961.png)

**Comment by LRufenacht** [comment]
Just needed to add border-radius: 0px for those panels. Fixed and checked in. Looks good, you can close it.
