### ISSUE TITLE
Html2Canvas: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#14]

**Comment by AlaaTrAce** [comment]
![msedge_GgpjrNfeqT](https://user-images.githubusercontent.com/57464198/157045078-b2e511ea-e5d7-4833-ad7b-a6f03a744d57.png)
![msedge_ouplgqGeN3](https://user-images.githubusercontent.com/57464198/157045142-ac50224d-ba3a-456e-a1b9-5fe5a47c203a.png)

- [x] Can download the screenshot
- [x] Ability to capture every component in the demo
- [x] Separate preview dialog

Something is off though, look at how the SVGs aren't rendered properly.

**Comment by LRufenacht** [comment]
Screenshots look okay to me.
I would...
- [ ] Remove the preview window and download a JPEG of the captured content.
- [ ] Make all button text use Title Casing.
- [ ] Remove the Wisej logo

**Comment by AlaaTrAce** [comment]
Sample just got updated

**Comment by LRufenacht** [comment]
*   [ ] Remove the "Capture" text from being repeated everywhere. Use a nice header (like the Examples header) for the FLP.
*   [ ] Remove the "Company Name" image and button.
*   [ ] Html Panel
*   [ ] Remove Demo button.

**Comment by AlaaTrAce** [comment]
![msedge_jY6Z1A4DWi](https://user-images.githubusercontent.com/57464198/157494818-9ba39cfc-7673-48f8-9ec6-a6c4d14386e3.png)

Updates pushed

**Comment by LRufenacht** [comment]
It shouldn't be called "Examples", call it "Screenshots" or something similar.

Maybe those options should have an accordion with a screenshot of the image and a "Refresh" button.

**Comment by AlaaTrAce** [comment]
I'll give it a try and give you feedback

**Comment by AlaaTrAce** [comment]
It didn't look that great, so I left it as is for now.

**Comment by LRufenacht** [comment]
Looks good, can close

**Comment by LRufenacht** [comment]
Add minimumSize for demo
