### ISSUE TITLE
Pannellum: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#17]

**Comment by LRufenacht** [comment]
*    [ ]  Need default image

**Comment by AlaaTrAce** [comment]
This one is fixed

**Comment by LRufenacht** [comment]
![](https://user-images.githubusercontent.com/21205878/157502237-08c01856-4490-4c34-9ff1-a113e0c076c8.png)

Simple should be selected by default.

**Comment by LRufenacht** [comment]
Actually, I would remove the Examples bar and list each one as an additional demo. "Simple" should be the only one in "Features".

**Comment by AlaaTrAce** [comment]
![msedge_8FWb7aHMH7](https://user-images.githubusercontent.com/57464198/157785150-f2de5499-e5fd-4944-bee1-91c4a7e78b42.png)

This looks to be completed, let me know if I can close it!

**Comment by LRufenacht** [comment]
Looks good!
