### ISSUE TITLE
RibbonBar: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#18]

**Comment by AlaaTrAce** [comment]
![msedge_0bT4b4PXVW](https://user-images.githubusercontent.com/57464198/157286983-6fe2d7c5-90c4-4ed4-bc0b-a6d259ae83f9.png)

**Comment by LRufenacht** [comment]
*    [ ]  Options -> Focusing TextBox only shows partial blue focus box.
*    [ ]  File button looks strange. "I" is capitalized. Should it have borders?
*    [ ]  Copy special... is cut off? 
*    [ ]  Use Title casing for all text.
*    [ ]  Don't show "Wisej.Web.Ext.RibbonBar.RibbonBarItem" in the AlertBox. User doesn't need to see this. Just show the name and value if it's a radio button.
*   [ ] Changing ComboBox value should fire an event.
*    [ ]  Make the Background White. Looks weird with the same background as the demo.
*    [ ]  Edit > Clicking an icon shows an AlertBox but the message doesn't let me determine which button is clicked.

**Comment by AlaaTrAce** [comment]
![msedge_ITTFms6z7W](https://user-images.githubusercontent.com/57464198/157784901-2e7e6a26-c357-4e66-a632-dbc587b5517b.png)

Fixed above issues except for the FocusBox one, it's an issue with the Bootstrap-4 theme, I couldn't figure out how to fix it :/
Can you please take care of it for me?

**Comment by LRufenacht** [comment]
Fixed and checked in. You could set the "shadowColor" style of the textbox in the RibbonBar mixin to transparent.

Can you please also move the RibbonBar mixin to the RibbonBar project and make sure it's an embedded resource?

**Comment by AlaaTrAce** [comment]
This one is already done, can it be closed?

**Comment by LRufenacht** [comment]
yes
