### ISSUE TITLE
ChartJS: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#19]

**Comment by AlaaTrAce** [comment]
![msedge_0zG7gPGQbG](https://user-images.githubusercontent.com/57464198/157286652-0eac5a63-9c93-4d51-8c0f-21a59f9c1146.png)

- [x] Wired ChartClick event
- [x] Multiple Chart types

**Comment by LRufenacht** [comment]
*    [ ]  I would take out three of the charts from this "Features" page. It looks a little too busy IMO. The Pie chart values are overlapping.
*    [ ]  Set a minimum Size for the demo.
*    [ ]  The AlertBoxes look weird being shown from the MiddleRight part of the screen. Try BottomRight and add a title so there isn't excessive blank space.

Looks good!

**Comment by LRufenacht** [comment]
Polar, donut, pie

**Comment by LRufenacht** [comment]
Or keep donut and see if that looks good.

**Comment by AlaaTrAce** [comment]
![msedge_CgR6uAnlSf](https://user-images.githubusercontent.com/57464198/157292302-f6fb1914-8a61-4c00-89b7-2db13d9564b7.png)
What do you think?

**Comment by LRufenacht** [comment]
![](https://user-images.githubusercontent.com/21205878/158214539-1dba6883-c9fe-4e26-878d-a9ff10c7b59a.png)

*   [ ] MinimumSize isn't right
