### ISSUE TITLE
ChartJS: Bubble

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#21]

**Comment by LRufenacht** [comment]
![](https://user-images.githubusercontent.com/21205878/158213883-a6c01604-fe2a-4a88-a2d3-e5db4f109630.png)

*   [ ] tooltip

**Comment by AlaaTrAce** [comment]
I think it would be best if you tackle this one, I couldn't figure out how to make it look like their demo: https://www.chartjs.org/docs/latest/charts/bubble.html

**Comment by LRufenacht** [comment]
Fixed, checked in GitHub.
