### ISSUE TITLE
ChartJS: Doughnut / Pie

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#22]

**Comment by LRufenacht** [comment]
![](https://user-images.githubusercontent.com/21205878/158213661-438a69c6-1fe6-49ee-b6e5-382d50e77e96.png)

*   [ ] tooltip

**Comment by AlaaTrAce** [comment]
![msedge_gYTdQpLQXX](https://user-images.githubusercontent.com/57464198/159538864-e604e42e-f21a-40ec-90f3-a5b83176c1df.png)
![msedge_z6p3ttdIfM](https://user-images.githubusercontent.com/57464198/159538876-52605802-3b57-4d48-a104-57a85278ae1c.png)

**Comment by LRufenacht** [comment]
Thx, can close
