### ISSUE TITLE
Link Source Code for each Demo to correct page in GitHub

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#3]
Each demo needs to have it's source code linked in the DemoBrowser.json file.

**Categories (Mark as checked after all contained demos are complete):**

*   [x] Editors
*   [x] Miscellaneous
*   [x] Containers
*   [x] Tools and Menus
*   [x] Extenders
*   [x] Content
*   [x] Buttons
*   [x] Grids
*   [x] Notifications
*   [x] Extensions
*   [x] Icon Packs

**Comment by AlaaTrAce** [comment]
Just pushed changes related to this one here, right now all available demos are correctly linked to their respective source code page.
