### ISSUE TITLE
ToolTip: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#32]

**Comment by AlaaTrAce** [comment]
![Web capture_23-3-2022_233956_localhost](https://user-images.githubusercontent.com/57464198/159807898-694ebdb2-0ec0-4cbc-afc4-44b33fafb0b9.jpeg)

- [x] Source code link
- [x] Description (en)
- [x] Minimum Size

**Comment by AlaaTrAce** [comment]
I'm re-imagining this one.

**Comment by LRufenacht** [comment]
Customizable Colors doesn't work. If it can't be fixed can you remove it?

**Comment by lucapivato** [comment]
Cannot work, there should be 1 ToolTip Extender on a container. Tooltips are shared. The ForeColor on the extender is set for the shared tooltip widget.

**Comment by lucapivato** [comment]
It can work if there is 1 extender and the properties are changed on the single extender.

**Comment by LRufenacht** [comment]
Update the issue when this is done, we're going live with it next week.

**Comment by AlaaTrAce** [comment]
Completely revamped the demo, now it's cleaner.

![chrome_3RUEmW7ZEC](https://user-images.githubusercontent.com/57464198/164953212-e8b246b0-2cb3-40a9-86d2-03927003bb81.png)

**Comment by AlaaTrAce** [comment]
Needs a few adjustments to the layout.
