### ISSUE TITLE
Add "Shape" Demo

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#33]

**Comment by LRufenacht** [comment]
@AlaaTrAce is there an update for this?

**Comment by AlaaTrAce** [comment]
Yeah, I pushed an update last week.

**Comment by LRufenacht** [comment]
Looks really good, nice!

![image](https://user-images.githubusercontent.com/21205878/164034215-a0bafe3a-8e60-45d6-baad-6d6454505bea.png)

- [ ] I would set the default shape background white and restore the demo background color.
- [ ] Same with "Appearances"
- [ ] Replace groupboxes with normal panels and use a label for the borderstyle text
- [ ] Align controls within each panel so they're centered

**Comment by LRufenacht** [comment]
Update the issue when this is done, we're going live with it next week.

**Comment by AlaaTrAce** [comment]
![chrome_BMpCGtJ7eT](https://user-images.githubusercontent.com/57464198/164953193-cac93682-c4b2-4424-8c35-49bdf94d33a4.png)
![chrome_enVMMapXtf](https://user-images.githubusercontent.com/57464198/164953194-e4fc466f-dc02-4d3d-9379-67c7de29d2f9.png)

Sample updated
