### ISSUE TITLE
Changing language does not work

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#40]
When I run it here, it preselects EN even though the texts display in german.
Changing the language from the ComboBox does not seem to have any effect, even with refreshing the page.

**Comment by FrankITG** [comment]
Also only some texts seem to be translated to german. 
Navigation commands like prev demo / next demo are not translated.
Please let me know if/when I should translate missing texts.

**Comment by AlaaTrAce** [comment]
Hi Frank, 

You can start translating right away if you feel like it.
Everything's located in the "DemoBrowser.json" file.

**Comment by LRufenacht** [comment]
Maybe we should take out the locale dropdown until all the translations are complete? It's pretty low-priority right now.

What do you think @FrankITG @AlaaTrAce

**Comment by FrankITG** [comment]
Yes, the way it is now it looks more like a bug than a missing feature.

**Comment by LRufenacht** [comment]
Sounds good, hid it for now.
