### ISSUE TITLE
Labels in TreeView sample are cut off

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#41]
![image](https://user-images.githubusercontent.com/37643082/162475983-cfb3aaf1-b45b-4fe0-82a6-8d25bef2337e.png)
See the 2 Multi- labels.

**Comment by AlaaTrAce** [comment]
It works perfectly fine for me!
![image](https://user-images.githubusercontent.com/57464198/162477758-b1d11e22-ce6d-4d3d-bf07-5ac85f16d290.png)

What happens when you switch to another Theme? Does it look the same or is it fixed?

**Comment by FrankITG** [comment]
It´s always cut off here. Switching themes does not help. Tested with .NET 4.8 and .NET 6.0.
In Chrome, Firefox & Edge.
Resolution 1920x1080 100%

**Comment by AlaaTrAce** [comment]
Could you try installing these fonts here?: [Open_Sans.zip](https://github.com/iceteagroup/Wisej-DemoBrowser/files/8453840/Open_Sans.zip)
It's a bit far fetched but I remember that installing the font actually fixed some issues.

**Comment by FrankITG** [comment]
Good idea, this fixes it.
We probably need to keep this in mind, once we share the source code for people to try the demobrowser on their own.

You can close this issue.

**Comment by LRufenacht** [comment]
Added a prompt on startup if the font isn't installed:
![image](https://user-images.githubusercontent.com/21205878/162510732-030f27b4-fefd-4a47-8f1f-66fedef70227.png)
