### ISSUE TITLE
DemoBrowser Fixes

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#42]
Hi Alaa,

Can you please fix these and close when finished?

- [x] Camera Minimum Size
- [x] ChartJS Charts lost on window resize (log if needed) ==> Couldn't reproduce.
- [x] jQueryKnob minimumsize
- [x] NavigationBar MinimumSize
- [x] OfficeViewer not showing up
- [x] ProgressCircle default Line cap selected in ComboBox.
- [x] ProgressCircle MinimumSize
- [x] ToolTip Customizable Colors doesn't work
- [x] ContextMenu MinimumSize
- [x] HelpTip MinimumSize
- [x] TabControl MinimumSize
- [x] FlexLayoutPanel MinimumSize

**Comment by AlaaTrAce** [comment]
Yes sir, 

I'll get everything fixed tonight.

**Comment by AlaaTrAce** [comment]
Updates were pushed, closing this for now.
