### ISSUE TITLE
Google Maps shows an error

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#44]
![image](https://user-images.githubusercontent.com/37643082/165192857-be11312f-ae9d-4b50-8d18-833e656c88c4.png)

**Comment by AlaaTrAce** [comment]
It looks like an error related to google cloud services?
That's what I understood from a console error.

**Comment by lucapivato** [comment]
It's normal. Related to the api key.

**Comment by LRufenacht** [comment]
Added a low-budget key so the error should be gone.
