### ISSUE TITLE
FontAwsome Icon Pack should be FontAwesome Icon Pack

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#46]
wrong name

**Comment by FrankITG** [comment]
Hi Alaa, is this already deployed? I sill see FontAwsome here
https://demo.wisej.com/Demos/#Icon%20Packs/FontAwsome

**Comment by AlaaTrAce** [comment]
Oops, my bad I guess I forgot to deploy the json file.
I'll do it later since Luca has to whitelist my IP again :/ .
