### ISSUE TITLE
TextBox multiline – tab key won't advance to next control when arrive in Multiline

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#47]
![image](https://user-images.githubusercontent.com/7750628/165211186-cd24a7da-ca05-452a-92f3-faf0efccdbf6.png)

**Comment by AlaaTrAce** [comment]
I think this is normal, it's a Multiline textbox and thus it handles the Tab Key differently.

**Comment by LRufenacht** [comment]
yes, it's correct.
