### ISSUE TITLE
Tab key – moving with tab through the controls and press “next demo” jump to video demo screen

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#49]
this occurs in various samples

Video with test
https://drive.google.com/file/d/1qCXbAgQpmIpgr4tJRBv91LaP387C3_7l/view?usp=sharing

**Comment by AlaaTrAce** [comment]
This looks like a very interesting bug.
Thanks Paul!

**Comment by LRufenacht** [comment]
Fixed and checked in.
The "Search Components" textbox was handling the tab key event and treating it like a search which cleared the treeview selection.
