### ISSUE TITLE
jSequence: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#5]

**Comment by LRufenacht** [comment]
![image](https://user-images.githubusercontent.com/21205878/156811697-586408dd-9203-434f-b2df-fd44b09a3e5f.png)

- [ ] Create nicer navigation for the four examples. Maybe use a FlowLayoutPanel with a few different options or a NavigationBar without the header.
- [ ] Standardize button size
- [ ] Standardize textbox widths
- [ ] Try to center jSequence widget in container or make container smaller.

**Comment by AlaaTrAce** [comment]
I think this looks better, waiting for your feedback so that I can do more cleaning
![msedge_tWE0FTlsFJ](https://user-images.githubusercontent.com/57464198/156886492-4f14064a-2a26-411a-b194-cc45f3fb923f.png)

**Comment by LRufenacht** [comment]
Take a look at how I adjusted the Example navigation.

Collapsed:
![image](https://user-images.githubusercontent.com/21205878/157077494-68c88711-d2e5-420b-844d-4416688bec86.png)

Expanded:
![image](https://user-images.githubusercontent.com/21205878/157077454-70c22220-4f67-4cc3-a8bc-374c23853bda.png)

Can you adjust the colors to match the theme, adjust the example names, and adjust the layout so it looks nice and centered?

**Comment by AlaaTrAce** [comment]
I just pushed some updates for this demo.

**Comment by AlaaTrAce** [comment]
![image](https://user-images.githubusercontent.com/57464198/157736028-23309dde-23c9-404f-a0f9-bc53b0d76b0a.png)

There's some issues in the current version that's fixed locally, I'll push them later with the remaining fixes.

**Comment by LRufenacht** [comment]
I tidied up this one. I didn't like the Configuration panel so I removed that and listed the other examples under "jSequence". I used the layout you had above for the controls. Also add overflow: visible to the jSequence widget so the values won't get cut off.

To finish this one up, can you

*   [ ] Set MinimumSize for all demos
*   [ ] Link source code
*   [ ] Add descriptions, if applicable

Thanks!

**Comment by AlaaTrAce** [comment]
This one is done too, I didn't find suitable descriptions for the other demos so I just left the default one.

**Comment by LRufenacht** [comment]
Can close
