### ISSUE TITLE
MenuBar features – Overflowicons  must show icons? 

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#52]
![image](https://user-images.githubusercontent.com/7750628/165212508-b4fdd240-d579-4471-b0f2-7a8081b1af33.png)

**Comment by AlaaTrAce** [comment]
No, It's supposed to display that "Burger Menu icon" to the right of the control.

**Comment by lucapivato** [comment]
It shows icons if the items have icons. Please add icons to all the menu items.
