### ISSUE TITLE
Split button – any button can’t select value from listed options

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#57]
On any split button, the selected option isn't showed after selected

![image](https://user-images.githubusercontent.com/7750628/165213280-483af462-9d49-4ed4-a771-1bbf337aa10d.png)

**Comment by lucapivato** [comment]
That's the correct behavior. Changing the button text is up to the application. You can modify the demo to do that.

**Comment by AlaaTrAce** [comment]
> That's the correct behavior. Changing the button text is up to the application. You can modify the demo to do that.

Checked in.
