### ISSUE TITLE
DevExtreme – dxFileManager link docs must be fixed

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#60]
I think this is the complete link

https://js.devexpress.com/Documentation/Guide/UI_Components/FileManager/Getting_Started_with_File_Manager/

![image](https://user-images.githubusercontent.com/7750628/165347327-b6239c64-9a03-4792-967c-f0b153438897.png)

**Comment by keevBush** [comment]
Fixed
