### ISSUE TITLE
DevExtreme -  dxHtmlEditor – update without changing params delete control toolbar

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#62]
![image](https://user-images.githubusercontent.com/7750628/165347850-8880ae6e-e0d6-44e6-94d3-82669f3cd0d7.png)

**Comment by keevBush** [comment]
Toolbar item ComboBox is empty

**Comment by LRufenacht** [comment]
@keevBush can you please set it so the default "update" does not change what's seen on the screen? Please update this thread when complete.

**Comment by keevBush** [comment]
Already fixed
