### ISSUE TITLE
ejPdfViewer  -error in dll pdfium.dll

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#70]
![image](https://user-images.githubusercontent.com/7750628/165405909-bd7fccae-4bf1-4438-b212-d58f4d287a32.png)

**Comment by LRufenacht** [comment]
Cannot reproduce @paulcordova @keevBush @FrankITG can you please get me the steps to reproduce?

**Comment by FrankITG** [comment]
Cannot reproduce either. Tested in Edge, Chrome and Firefox. All work ok here.

**Comment by LRufenacht** [comment]
@paulcordova do you have a video of this?

**Comment by paulcordova** [comment]
Tested Ok in Chrome

![image](https://user-images.githubusercontent.com/7750628/166570020-3722c764-c9a0-4f6b-8c15-b6c601e81f43.png)
