### ISSUE TITLE
ejPivotTreeMap – dont show control and property raise an error

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#74]
![image](https://user-images.githubusercontent.com/7750628/165406358-2b8ec832-a9ba-4b03-97b7-9f78ad4070ba.png)

**Comment by LRufenacht** [comment]
In the Syncfusion docs it's listed as getJSONRecords (https://help.syncfusion.com/api/js/ejpivottreemap#methods:getjsonrecords).
In the actual implementation it's getJsonRecords().

Fixed and checked in SVN.
