### ISSUE TITLE
Designer doesn't load ui of Premium extension

### ISSUE THREAD

**Issue by keevBush** [iceteagroup/Wisej-DemoBrowser#77]
- **Wisej version** : 3.0.7.5
- **Premium extension** : EJ2 Syncfusion 2
- **Resume**: Designer doesn't load current widget and set this error message : Unknow type : wisej.web.ext.Syncfusion2Widget
- **Video**: https://drive.google.com/file/d/1ecCLf964UDd4bIXZQaxrHfLOsKMFtoGG/view?usp=sharing

**Comment by AlaaTrAce** [comment]
![image](https://user-images.githubusercontent.com/57464198/165759261-6729579a-b755-44c8-8ef3-fd6ecbceabd1.png)

Cannot reproduce, sometimes JS widgets fail to initialize properly but it's really rare. if you close that designer and re-open it it should be fine.
