### ISSUE TITLE
FlowLayoutPanel sample not very intuitive

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#78]
https://demo.wisej.com/Demos/#Containers/FlowLayoutPanel

While it is technically correct, I think the FlowLayoutPanel is not very intuitive.
The difference between LeftToRight and TopToBottom is hard to notice.
Maybe rather use some shapes or colors to better show the difference?

**Comment by LRufenacht** [comment]
What do you think of this? https://watch.screencastify.com/v/yBkwIdklQIYABaqadyy5

**Comment by FrankITG** [comment]
Much cleaner! Thx Levie.
