### ISSUE TITLE
Update PropertyGrid: Features

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#8]
I think we should switch this demo to a PropertyGrid that allows you to edit a given class (i.e. Person). 

When changing the values in the PropertyGrid update TextBoxes or an image of the person to represent the new values.

**Comment by AlaaTrAce** [comment]
What do you think about this?
![msedge_1hw66N1aXl](https://user-images.githubusercontent.com/57464198/156217786-83bc36ec-1033-461b-9c5e-459ba81ce17c.png)

**Comment by LRufenacht** [comment]
That works! Try to add several different data types so the users can play with a color picker, boolean toggle, text entry, etc.

**Comment by LRufenacht** [comment]
![image](https://user-images.githubusercontent.com/21205878/156796045-46238a22-e1f3-4f2d-adb6-a6b84261a61c.png)

- [ ]  Update Description: The <b>Wisej.Web.PropertyGrid</b> provides a user interface for browsing the properties of an object.
- [ ] Docs links doesn't work
- [ ] Source code link should go directly to the demo in GitHub
- [ ] Remove GroupBox around PropertyGrid
- [ ] Can you add descriptions for the property in the PropertyGrid?
- [ ] Update "Misc" title on PropertyGrid to something more descriptive
- [ ] Center the ID Card
- [ ] Favorite Color should have a label describing it on the ID card

Other than that, looks good!

**Comment by AlaaTrAce** [comment]
What do you think of this one here?
![msedge_c2ss3CMBP8](https://user-images.githubusercontent.com/57464198/156886535-2aa2b3a6-5e88-4c55-b749-a5982d74cd04.png)

**Comment by LRufenacht** [comment]
Bettter!
Cardholder is one word.
Add a period after all the descriptions.
You can move the Wisej logo to the top left-hand or right-hand corner.

**Comment by LRufenacht** [comment]
Random alertbox when opening the demo. Should be removed

**Comment by LRufenacht** [comment]
Then you can close it

**Comment by AlaaTrAce** [comment]
Done.
