### ISSUE TITLE
SyncFusion ext2 - Cant load samples - runned on browser

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#80]
This happend  when try to run syncfusion2 demos
![Wisej-DemoBrowser-SyncFusion2-Error](https://user-images.githubusercontent.com/7750628/166464396-71a7a529-9d89-43c2-8caa-4385c34409a6.gif)

**Comment by LRufenacht** [comment]
Should be fixed.

**Comment by paulcordova** [comment]
Fixed

![image](https://user-images.githubusercontent.com/7750628/166521356-32d1bc84-68f2-42a0-943f-deb25575d282.png)
