### ISSUE TITLE
Add Icons for Toolbar

### ISSUE THREAD

**Issue by LRufenacht** [iceteagroup/Wisej-DemoBrowser#85]
All items should have an icon
![image](https://user-images.githubusercontent.com/21205878/166582855-c801e329-aba0-4bd5-86f6-fbeba4008b68.png)

**Comment by LRufenacht** [comment]
@AlaaTrAce please notify and close when complete

**Comment by AlaaTrAce** [comment]
Updated, also improved the layout a little bit
