### ISSUE TITLE
JustGage: Features

### ISSUE THREAD

**Issue by AlaaTrAce** [iceteagroup/Wisej-DemoBrowser#9]

**Comment by LRufenacht** [comment]
![image](https://user-images.githubusercontent.com/21205878/156812752-4950d513-c0a8-4ea5-a67a-369ce72ddbc7.png)

- [ ] Add MinimumSize to demo
- [ ] Update description, look at https://toorshia.github.io/justgage/#about
- [ ] Docs link doesn't work

**Comment by AlaaTrAce** [comment]
> [ ] Changing value then changing another property breaks value.

Can you please send me a video ? I wasn't able to "break" it

**Comment by LRufenacht** [comment]
When first clicking the demo:
![image](https://user-images.githubusercontent.com/21205878/157094025-84d87c09-ead8-4ff6-984d-4266e28ce024.png)

Label shows 0. Not sure if this is a Wisej bug or something in the sample. Should be 50.

**Comment by LRufenacht** [comment]
https://watch.screencastify.com/v/qDIanwsFPCTzVSqatqQQ

**Comment by AlaaTrAce** [comment]
Okay this is weird, it works fine on my end

https://user-images.githubusercontent.com/57464198/157094731-627a79ec-1aff-4f2f-8203-658bfa0fffbf.mp4

**Comment by LRufenacht** [comment]
Actually,

Can you try the sample with Chrome to reproduce the issue above? It looks like you're using Edge in the video above.

The other issue is... setting the Decimal places doesn't seem to work correctly.

**Comment by AlaaTrAce** [comment]
https://user-images.githubusercontent.com/57464198/157287845-6fba51c8-5d42-4653-8401-986ed600a11c.mp4

It's working fine, tested on Chromium (the most broken thing ever, even more broken than a chrome canary build) and a stable Chrome browser

I'll fix the NumericUpDown control to add decimals.

**Comment by LRufenacht** [comment]
Thanks,

You can close when finished.
